os:
  - linux
env:
  matrix:
    - TAG=latest                    OS=alpine:3.5     OPAM=1.2.2 OCAML=4.04.1
    - TAG=alpine3.5_ocaml4.06.0     OS=alpine:3.5     OPAM=1.2.2 OCAML=4.06.0+trunk
    - TAG=alpine3.5_ocaml4.05.0     OS=alpine:3.5     OPAM=1.2.2 OCAML=4.05.0+trunk
    - TAG=alpine3.5_ocaml4.04.1     OS=alpine:3.5     OPAM=1.2.2 OCAML=4.04.1
    - TAG=alpine3.5_ocaml4.03.0     OS=alpine:3.5     OPAM=1.2.2 OCAML=4.03.0
    - TAG=alpine3.5_ocaml4.02.3     OS=alpine:3.5     OPAM=1.2.2 OCAML=4.02.3
    - TAG=alpine3.5_ocaml4.01.0     OS=alpine:3.5     OPAM=1.2.2 OCAML=4.01.0
    - TAG=alpine3.5_ocaml4.00.1     OS=alpine:3.5     OPAM=1.2.2 OCAML=4.00.1
    - TAG=centos7_ocaml4.06.0       OS=centos:7       OPAM=1.2.2 OCAML=4.06.0+trunk
    - TAG=centos7_ocaml4.05.0       OS=centos:7       OPAM=1.2.2 OCAML=4.05.0+trunk
    - TAG=centos7_ocaml4.04.1       OS=centos:7       OPAM=1.2.2 OCAML=4.04.1
    - TAG=centos7_ocaml4.03.0       OS=centos:7       OPAM=1.2.2 OCAML=4.03.0
    - TAG=centos7_ocaml4.02.3       OS=centos:7       OPAM=1.2.2 OCAML=4.02.3
    - TAG=centos7_ocaml4.01.0       OS=centos:7       OPAM=1.2.2 OCAML=4.01.0
    - TAG=centos7_ocaml4.00.1       OS=centos:7       OPAM=1.2.2 OCAML=4.00.1
    - TAG=centos6_ocaml4.06.0       OS=centos:6       OPAM=1.2.2 OCAML=4.06.0+trunk
    - TAG=centos6_ocaml4.05.0       OS=centos:6       OPAM=1.2.2 OCAML=4.05.0+trunk
    - TAG=centos6_ocaml4.04.1       OS=centos:6       OPAM=1.2.2 OCAML=4.04.1
    - TAG=centos6_ocaml4.03.0       OS=centos:6       OPAM=1.2.2 OCAML=4.03.0
    - TAG=centos6_ocaml4.02.3       OS=centos:6       OPAM=1.2.2 OCAML=4.02.3
    - TAG=centos6_ocaml4.01.0       OS=centos:6       OPAM=1.2.2 OCAML=4.01.0
    - TAG=centos6_ocaml4.00.1       OS=centos:6       OPAM=1.2.2 OCAML=4.00.1
    - TAG=debian8_ocaml4.06.0       OS=debian:8       OPAM=1.2.2 OCAML=4.06.0+trunk
    - TAG=debian8_ocaml4.05.0       OS=debian:8       OPAM=1.2.2 OCAML=4.05.0+trunk
    - TAG=debian8_ocaml4.04.1       OS=debian:8       OPAM=1.2.2 OCAML=4.04.1
    - TAG=debian8_ocaml4.03.0       OS=debian:8       OPAM=1.2.2 OCAML=4.03.0
    - TAG=debian8_ocaml4.02.3       OS=debian:8       OPAM=1.2.2 OCAML=4.02.3
    - TAG=debian8_ocaml4.01.0       OS=debian:8       OPAM=1.2.2 OCAML=4.01.0
    - TAG=debian8_ocaml4.00.1       OS=debian:8       OPAM=1.2.2 OCAML=4.00.1
    - TAG=ubuntu16.04_ocaml4.06.0   OS=ubuntu:16.04   OPAM=1.2.2 OCAML=4.06.0+trunk
    - TAG=ubuntu16.04_ocaml4.05.0   OS=ubuntu:16.04   OPAM=1.2.2 OCAML=4.05.0+trunk
    - TAG=ubuntu16.04_ocaml4.04.1   OS=ubuntu:16.04   OPAM=1.2.2 OCAML=4.04.1
    - TAG=ubuntu16.04_ocaml4.03.0   OS=ubuntu:16.04   OPAM=1.2.2 OCAML=4.03.0
    - TAG=ubuntu16.04_ocaml4.02.3   OS=ubuntu:16.04   OPAM=1.2.2 OCAML=4.02.3
    - TAG=ubuntu16.04_ocaml4.01.0   OS=ubuntu:16.04   OPAM=1.2.2 OCAML=4.01.0
    - TAG=ubuntu16.04_ocaml4.00.1   OS=ubuntu:16.04   OPAM=1.2.2 OCAML=4.00.1

language: c
sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - ./generate.sh > Dockerfile
  - docker build -t akabe/ocaml:$TAG .
  - docker history --no-trunc akabe/ocaml:$TAG

script:
  - docker run --rm -v $PWD:$PWD -w $PWD/tests akabe/ocaml:$TAG sh run_test.sh

after_success:
  - |-
    if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == master ]]; then
      docker login -u $DOCKER_USER -p $DOCKER_PWD
      docker push akabe/ocaml:$TAG
    else
      echo -e "\033[33mSkip deploying image to DockerHub...\033[0m"
    fi
