language: c
sudo: required
dist: trusty
group: edge
cache: apt
os:
  - linux
services:
  - docker

matrix:
  include:
    - env: BASE_TAG=alpine-3.10 OCAML=4.09.0 TAGS='4.09.0 4.09 alpine3.10_ocaml4.09.0 latest'
    - env: BASE_TAG=alpine-3.10 OCAML=4.08.1 TAGS='4.08.1 4.08 alpine3.10_ocaml4.08.1'
    - env: BASE_TAG=alpine-3.9  OCAML=4.09.0 TAGS='alpine3.9_ocaml4.09.0'
    - env: BASE_TAG=alpine-3.9  OCAML=4.08.1 TAGS='alpine3.9_ocaml4.08.1'

script:
  - docker build --rm --build-arg BASE_TAG=$BASE_TAG --build-arg OCAML_VERSION=$OCAML -t akabe/ocaml:fresh dockerfiles/
  - docker history akabe/ocaml:fresh
after_success:
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == false ]] && [[ "$TRAVIS_BRANCH" == master ]]
    then
      docker login -u $DOCKER_USER -p $DOCKER_PWD
      for t in ${TAGS[@]}; do
        docker tag akabe/ocaml:fresh akabe/ocaml:$t
        docker push akabe/ocaml:$t
      done
    fi
