language: c
sudo: required
dist: trusty
group: edge
cache: apt
os:
  - linux
services:
  - docker

matrix:
  include:
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.07.0       TAGS='alpine3.5_ocaml4.07.0 alpine_ocaml4.07.0 4.07.0'
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.06.1       TAGS='alpine3.5_ocaml4.06.1 alpine_ocaml4.06.1 4.06.1'
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.05.0       TAGS='alpine3.5_ocaml4.05.0 alpine_ocaml4.05.0 4.05.0'
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.04.2       TAGS='alpine3.5_ocaml4.04.2 alpine_ocaml4.04.2 4.04.2'
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.03.0       TAGS='alpine3.5_ocaml4.03.0 alpine_ocaml4.03.0 4.03.0'
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.02.3       TAGS='alpine3.5_ocaml4.02.3 alpine_ocaml4.02.3 4.02.3'
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.01.0       TAGS='alpine3.5_ocaml4.03.0 alpine_ocaml4.01.0 4.01.0'
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.00.1       TAGS='alpine3.5_ocaml4.00.1 alpine_ocaml4.00.1 4.00.1'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.07.0       TAGS='centos7_ocaml4.07.0 centos_ocaml4.07.0'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.06.1       TAGS='centos7_ocaml4.06.1 centos_ocaml4.06.1'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.05.0       TAGS='centos7_ocaml4.05.0 centos_ocaml4.05.0'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.04.2       TAGS='centos7_ocaml4.04.2 centos_ocaml4.04.2'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.03.0       TAGS='centos7_ocaml4.03.0 centos_ocaml4.03.0'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.02.3       TAGS='centos7_ocaml4.02.3 centos_ocaml4.02.3'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.01.0       TAGS='centos7_ocaml4.03.0 centos_ocaml4.01.0'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.00.1       TAGS='centos7_ocaml4.00.1 centos_ocaml4.00.1'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.07.0       TAGS='centos6_ocaml4.07.0'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.06.1       TAGS='centos6_ocaml4.06.1'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.05.0       TAGS='centos6_ocaml4.05.0'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.04.2       TAGS='centos6_ocaml4.04.2'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.03.0       TAGS='centos6_ocaml4.03.0'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.02.3       TAGS='centos6_ocaml4.02.3'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.01.0       TAGS='centos6_ocaml4.03.0'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.00.1       TAGS='centos6_ocaml4.00.1'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.07.0       TAGS='debian8_ocaml4.07.0 debian_ocaml4.07.0'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.06.1       TAGS='debian8_ocaml4.06.1 debian_ocaml4.06.1'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.05.0       TAGS='debian8_ocaml4.05.0 debian_ocaml4.05.0'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.04.2       TAGS='debian8_ocaml4.04.2 debian_ocaml4.04.2'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.03.0       TAGS='debian8_ocaml4.03.0 debian_ocaml4.03.0'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.02.3       TAGS='debian8_ocaml4.02.3 debian_ocaml4.02.3'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.01.0       TAGS='debian8_ocaml4.03.0 debian_ocaml4.01.0'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.00.1       TAGS='debian8_ocaml4.00.1 debian_ocaml4.00.1'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.07.0       TAGS='ubuntu16.04_ocaml4.07.0 ubuntu_ocaml4.07.0'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.06.1       TAGS='ubuntu16.04_ocaml4.06.1 ubuntu_ocaml4.06.1'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.05.0       TAGS='ubuntu16.04_ocaml4.05.0 ubuntu_ocaml4.05.0'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.04.2       TAGS='ubuntu16.04_ocaml4.04.2 ubuntu_ocaml4.04.2'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.03.0       TAGS='ubuntu16.04_ocaml4.03.0 ubuntu_ocaml4.03.0'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.02.3       TAGS='ubuntu16.04_ocaml4.02.3 ubuntu_ocaml4.02.3'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.01.0       TAGS='ubuntu16.04_ocaml4.03.0 ubuntu_ocaml4.01.0'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.00.1       TAGS='ubuntu16.04_ocaml4.00.1 ubuntu_ocaml4.00.1'
  allow_failures:
    # OCaml 4.04.2 often fails due to stack overflow
    - env: BASE=alpine:3.5   OPAM=1.2.2 OCAML=4.04.2       TAGS='alpine3.5_ocaml4.04.2 alpine_ocaml4.04.2 4.04.2'
    - env: BASE=centos:7     OPAM=1.2.2 OCAML=4.04.2       TAGS='centos7_ocaml4.04.2 centos_ocaml4.04.2'
    - env: BASE=centos:6     OPAM=1.2.2 OCAML=4.04.2       TAGS='centos6_ocaml4.04.2'
    - env: BASE=debian:8     OPAM=1.2.2 OCAML=4.04.2       TAGS='debian8_ocaml4.04.2 debian_ocaml4.04.2'
    - env: BASE=ubuntu:16.04 OPAM=1.2.2 OCAML=4.04.2       TAGS='ubuntu16.04_ocaml4.04.2 ubuntu_ocaml4.04.2'

script:
  - bash -eu travis-ci.sh
